### ISSUE TITLE
CenterWindow.ahk not friendly with multiple monitors

### ISSUE THREAD

**Issue by Darxide23** [TCNOco/TcNo-Random-Scripts#1]
This script always sends windows to the main monitor. Would there be a way to alter it so windows center in whichever monitor they are already in?

**Comment by TCNOco** [comment]
I'm not able to get to this at the moment, but the Wiki has good info about this. For me, this works well and puts windows directly in the centre of my 3 monitors.

See:
- [WinMove](https://www.autohotkey.com/docs/commands/WinMove.htm) - Search for `multi-monitor systems`
- [WinPos](https://www.autohotkey.com/docs/commands/WinGetPos.htm) - I would assume you'd do some math to see what monitor it's on by getting the X and Y values as well... Then, over the total size of all your monitors, see which is which, and move accordingly.

I haven't given this much thought as it's not a use-case for me. I like moving from EVERYWHERE to the center of everything, works well for video recording.

Do let me know if you figure something out, would be useful to add something like this :)

**Comment by Darxide23** [comment]
This works.

#c::
winHandle := WinExist("A") ; The window to operate on

; get the bounding coordinates of the monitor the window is on:
;--------------------------------------------------------------------------
VarSetCapacity(monitorInfo, 40), NumPut(40, monitorInfo)
monitorHandle := DllCall("MonitorFromWindow", "Ptr", winHandle, "UInt", 0x2)
DllCall("GetMonitorInfo", "Ptr", monitorHandle, "Ptr", &monitorInfo)
;--------------------------------------------------------------------------

workLeft      := NumGet(monitorInfo, 20, "Int") ; Left
workTop       := NumGet(monitorInfo, 24, "Int") ; Top
workRight     := NumGet(monitorInfo, 28, "Int") ; Right
workBottom    := NumGet(monitorInfo, 32, "Int") ; Bottom
WinGetPos,,, W, H, A
WinMove, A,, workLeft + (workRight - workLeft) // 2 - W // 2
    , workTop + (workBottom - workTop) // 2 - H // 2

**Comment by TCNOco** [comment]
Thanks for suggesting this. I've included this and credited you :)
